"Filed out from Dolphin Smallalk"!

JadeSessionManager subclass: #ContactsSessionManager
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ContactsSessionManager guid: (GUID fromString: '{639e76e3-b3c9-4dce-a9eb-f50b3d878ac8}')!
ContactsSessionManager comment: ''!
!ContactsSessionManager categoriesForClass!Unclassified! !
!ContactsSessionManager class methodsFor!

mainShellClass

	^ContactsLoginShell.
! !
!ContactsSessionManager class categoriesForMethods!
mainShellClass!public! !
!

