"Filed out from Dolphin Smallalk"!

MCFileBasedRepository subclass: #MCDirectoryRepository
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MCDirectoryRepository guid: (GUID fromString: '{8b1b9ee6-fa9a-4e55-93e0-873c1f44b600}')!
MCDirectoryRepository comment: ''!
!MCDirectoryRepository categoriesForClass!Unclassified! !
!MCDirectoryRepository methodsFor!

updateVersionDialogTabIn: aMCVersionDialog

	aMCVersionDialog updateDirectoryTabWith: self.
! !
!MCDirectoryRepository categoriesForMethods!
updateVersionDialogTabIn:!public! !
!

